### ISSUE TITLE
Idea: Naked objects pattern

### ISSUE THREAD

**Issue by probar** [CrowdHailer/just-job#8]
Interesting project. I wonder though, if for simple projects, adding something like the naked-objects(even in textual form) pattern would make sense, and automatically will create the interactors.

**Comment by CrowdHailer** [comment]
Sounds interesting. Would you be able to expand a bit on what you mean by the naked object pattern.

**Comment by probar** [comment]
Basically , if you build "rich" domain models , that includes data and methods("actions) following the pattern, there's a framework that can automatically create a full GUI interface based on that, that allows the user to have full functionality(albeit usually not the ideal UI) - which is great for prototyping and verification by domain experts.

more here:

http://www.infoq.com/articles/haywood-ddd-no 

Also Google Apache ISIS.
